@startuml 

title Chocolate factory model

hide circle
skinparam handwritten true
skinparam useBetaStyle true

class "s4bldg:PhysicalObject" as physicalObject
class "s4bldg:BuildingSpace" as space
class "s4bldg:Building" as building

class "s4inma:Factory" as factory
building <|-- factory
building --> space : s4bldg:hasSpace

class "s4inma:Site" as site
class "s4inma:Area" as area
space <|-- site
space <|-- area

building --> physicalObject : s4bldg:contains

class "saref:Device" as device {
    manufacturer
    model
}
class "saref:Function" as function
device --> function : saref:hasFunction

class "saref:Sensor" as sensor
class "saref:TemperatureSensor" as temperatureSensor
device <|-- sensor
sensor <|-- temperatureSensor

class "s4inma:WorkCenter" as workCenter
class "ProductionLineWorkCenter" as line
class "StorageRoomWorkCenter" as store

physicalObject <|-- productionEquipment
device <|-- productionEquipment
productionEquipment <|-- workCenter
workCenter <|-- line
workCenter <|-- store

class "s4inma:ProductionEquipment" as productionEquipment
class "FanningProductionEquipment" as fan
class "GrindingProductionEquipment" as grinder
class "MouldingProductionEquipment" as mould

productionEquipment <|-- fan
productionEquipment <|-- grinder
productionEquipment <|-- mould

class "s4inma:ProductionEquipmentFunction" as productionEquipmentFunction
function <|-- productionEquipmentFunction

class "s4inma:ProductionEquipmentCategory" as productionEquipmentCategory
productionEquipment --> productionEquipmentCategory : s4inma:belongsToCategory

' actual features of interest (that have measurements) are batches

class FormingFunction
class GridingFunction
class RoastingFunction

productionEquipmentFunction <|-- FormingFunction
productionEquipmentFunction <|-- GridingFunction
productionEquipmentFunction <|-- RoastingFunction

class "saref:FeatureOfInterest" as feature
class "s4inma:Batch" as batch {
    identifier
    beginning
    end
}
class "s4inma:MaterialBatch" as materialBatch
feature <|-- batch
batch <|-- materialBatch
batch --> productionEquipment : s4inma:needsEquipment

class "saref:Property" as property
class "saref:Temperature" as temperature
class "RoastingTemperature" as roastingTemperature
property <|-- temperature
temperature <|-- roastingTemperature
feature --> property : saref:hasProperty
property --> device : saref:isMeasuredByDevice

class "saref:Measurement" as measurement {
    measuredIn
    timestamp
    value
}
class "s4inma:Measurement" as inmaMeasurement
class "s4inma:ActualMeasurement" as actualMeasurement
measurement <|-- inmaMeasurement
inmaMeasurement <|-- actualMeasurement
measurement --> property : saref:relatesToProperty

@enduml